// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABopAeteEsS12ssJBa1rk0nHXM1MedS0Q',
    appId: '1:129731309553:web:8fba2ee07a2731ee6a1e50',
    messagingSenderId: '129731309553',
    projectId: 'laotrust-web',
    authDomain: 'laotrust-web.firebaseapp.com',
    storageBucket: 'laotrust-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGI2B_biMzMkKdJSdjkqG41w6GwESCho',
    appId: '1:129731309553:android:b2f285f08ac350006a1e50',
    messagingSenderId: '129731309553',
    projectId: 'laotrust-web',
    storageBucket: 'laotrust-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvILXkKXqBGzrzyERaAH8LRCifC7bSVys',
    appId: '1:129731309553:ios:b055063fe0a1ecf16a1e50',
    messagingSenderId: '129731309553',
    projectId: 'laotrust-web',
    storageBucket: 'laotrust-web.firebasestorage.app',
    iosBundleId: 'com.laotrust.app',
  );
}
